##############
### Spring ###
##############
spring:

  ################
  ### Database ###
  ################
  datasource:
    url: jdbc:postgresql://${DB_URI:localhost}:${DB_PORT:5432}/autorepairshop
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  ###########
  ### JPA ###
  ###########
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: autorepairshop
    open-in-view: false