##############
### Logger ###
##############
logging:
  level:
    sql: WARN
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.flywaydb.core.internal.scanner: DEBUG

##############
### Server ###
##############
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

##############
### Spring ###
##############
spring:
  messages:
    encoding: UTF-8
  flyway:
    schemas: autorepairshop
    enabled: true
    locations: classpath:db/migration,classpath:db/callbacks
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Initial baseline"
    validate-on-migrate: true
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    fail-on-missing-locations: true

  application:
    name: autorepairshop

  ################
  ### Profile ###
  ################
  profiles:
    active: dev

  ################
  ### Database ###
  ################
  datasource:
    url: jdbc:postgresql://${DB_URI:localhost}:${DB_PORT:5432}/autorepairshop
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  ###########
  ### JPA ###
  ###########
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: autorepairshop
    open-in-view: false

  #############
  ### Redis ###
  #############
  data:
    redis:
      host: ${REDIS_URI:localhost}
      port: ${REDIS_PORT:6379}
      timeout: ${REDIS_TIMEOUT:3000ms}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  #############
  ### Redis ###
  #############
  security:
    security-key: ${SECURITY_KEY:6c9c5acb3e09048b863a865d1b524c935b9cfe8c401a1d5396cd63749e02f89427d9543b31d9c0ea1e88089f8412932e2886b273d7bc7920bea814b847dc7ad1}
    token-expiration: ${TOKEN_EXPIRATION:14400000}


  ##################
  ###### Email #####
  ##################
  mail:
    host: smtp.gmail.com
    port: 587
    username: autorepairshopsoat@gmail.com
    password: yiar udky muhb kuiy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


company:
  email: autorepairshopsoat@gmail.com


management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,metrics"
  metrics:
    tags:
      enabled: true

##################
### Swagger UI ###
##################
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    resolve-schema-properties: true